name: salida manual

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * 1-4'   # Lunes a jueves a las 18:00 (UTC = 20:00 CET)
    - cron: '0 12 * * 5'     # Viernes a las 14:00 (UTC = 16:00 CET)

jobs:
  salida:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: npm install

      - name: Instalar navegadores de Playwright
        run: npx playwright install --with-deps

      - name: Ejecutar salida
        run: npm run salida
        
        env:
          COMPANY_ID: ${{ secrets.COMPANY_ID }}
          USER_NAME: ${{ secrets.USER_NAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          ACTION: clockout

      - name: Subir capturas de pantalla si falla
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: capturas-fallo
          path: |
            *.png
